[project]
name = "online-market-project"
version = "0.1.0"
description = ""
authors = [
    {name = "rybin",email = "rybin.32@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.3.0"
black = "^25.9.0"
isort = "^6.0.1"
mypy = "^1.18.2"

